-- MySQL Script generated by MySQL Workbench
-- dom 03 mar 2019 04:37:33 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema framework_testing
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema framework_testing
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `framework_testing` DEFAULT CHARACTER SET utf8 ;
USE `framework_testing` ;

-- -----------------------------------------------------
-- Table `framework_testing`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `framework_testing`.`role` (
  `role_id` INT NOT NULL,
  `role_desc` VARCHAR(45) NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `role_id_UNIQUE` (`role_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `framework_testing`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `framework_testing`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_nick` VARCHAR(45) NULL,
  `user_name` VARCHAR(45) NULL,
  `user_lastname` VARCHAR(45) NULL,
  `user_email` VARCHAR(45) NULL,
  `user_password` VARCHAR(45) NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  UNIQUE INDEX `user_nick_UNIQUE` (`user_nick` ASC),
  UNIQUE INDEX `user_email_UNIQUE` (`user_email` ASC),
  INDEX `fk_user_role_idx` (`role_id` ASC),
  CONSTRAINT `fk_user_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `framework_testing`.`role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
